#!/usr/bin/env node
import { mkdir, readFile, symlink, writeFile } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DATA_DIR = process.env.PI_WEB_DATA_DIR ?? "~/.pi-web";
const DEFAULT_PLUGIN_SOURCE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_PLUGIN_LINK = `${DATA_DIR}/plugins/telegram-gateway`;
const DEFAULT_CONFIG_PATH = `${DATA_DIR}/telegram-gateway/config.json`;

main().catch((error) => {
  console.error(`\nSetup failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});

async function main() {
  const rl = createInterface({ input, output });
  try {
    console.log("PI WEB Telegram Gateway setup\n");
    console.log("Before continuing, create a bot with @BotFather and copy its token.\n");

    const token = process.env.TELEGRAM_BOT_TOKEN ?? await askRequiredSecret(rl, "Telegram bot token (input is visible; prefer TELEGRAM_BOT_TOKEN)");
    const bot = await telegram(token, "getMe", {});
    console.log(`Connected to @${bot.username ?? bot.first_name ?? "your bot"}.`);

    console.log("\nNow open Telegram, send /start to your bot, then press Enter here.");
    await rl.question("Press Enter after you send /start: ");
    const userId = await discoverTelegramUserId(token, rl);

    const cwdDefault = process.cwd();
    const defaultCwd = await askAbsolutePath(rl, `Default PI WEB workspace`, cwdDefault);
    const piWebBaseUrl = await askWithDefault(rl, "PI WEB base URL", "http://127.0.0.1:8504");
    const configPath = expandHome(await askWithDefault(rl, "Config path", DEFAULT_CONFIG_PATH));

    const config = {
      $schemaComment: "Generated by setup.mjs. Prefer TELEGRAM_BOT_TOKEN env var over storing a token here.",
      telegramBotToken: "",
      piWebBaseUrl,
      machineId: "local",
      defaultCwd,
      allowedTelegramUserIds: [userId],
      adminTelegramUserIds: [userId],
      userRoutes: {
        [String(userId)]: { label: "Owner", cwd: defaultCwd },
      },
      statePath: `${DATA_DIR}/telegram-gateway/state.json`,
      pollTimeoutSeconds: 25,
      requestTimeoutMs: 30000,
      responseTimeoutMs: 900000,
      maxTelegramChunk: 3900,
    };

    await mkdir(dirname(configPath), { recursive: true });
    await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, { mode: 0o600 });

    await maybeInstallPluginLink(rl);

    console.log("\nSetup complete. Start the gateway with:\n");
    console.log(`TELEGRAM_BOT_TOKEN='${redactToken(token)}' node ${expandHome(DEFAULT_PLUGIN_LINK)}/gateway.mjs --config ${configPath}`);
    console.log("\nUse the real token in the env var above. Do not commit it to git.");
  } finally {
    rl.close();
  }
}

async function maybeInstallPluginLink(rl) {
  const install = await askYesNo(rl, `Symlink this plugin into ${DATA_DIR}/plugins now?`, true);
  if (!install) return;
  const source = resolve(await askWithDefault(rl, "Plugin source path", DEFAULT_PLUGIN_SOURCE));
  const link = expandHome(await askWithDefault(rl, "Plugin link path", DEFAULT_PLUGIN_LINK));
  await mkdir(dirname(link), { recursive: true });
  try {
    await symlink(source, link, "dir");
    console.log(`Linked ${link} -> ${source}`);
  } catch (error) {
    if (error && error.code === "EEXIST") {
      console.log(`Plugin link already exists: ${link}`);
      return;
    }
    throw error;
  }
}

async function discoverTelegramUserId(token, rl) {
  for (let attempt = 1; attempt <= 6; attempt += 1) {
    const updates = await telegram(token, "getUpdates", { timeout: 3, allowed_updates: ["message"] });
    const users = [];
    for (const update of updates) {
      const from = update.message?.from;
      if (typeof from?.id === "number") users.push(from);
    }
    const uniqueUsers = [...new Map(users.map((user) => [user.id, user])).values()];
    if (uniqueUsers.length === 1) {
      const user = uniqueUsers[0];
      console.log(`Detected Telegram user: ${formatUser(user)}`);
      return user.id;
    }
    if (uniqueUsers.length > 1) {
      console.log("Detected multiple Telegram users:");
      for (const user of uniqueUsers) console.log(`- ${formatUser(user)}`);
      const answer = await askWithDefault(rl, "Which numeric user ID should be admin?", String(uniqueUsers[0].id));
      const id = Number(answer);
      if (Number.isInteger(id)) return id;
    }
    console.log(`No /start message found yet (${attempt}/6). Send /start to the bot in Telegram.`);
  }
  const manual = await askWithDefault(rl, "Telegram numeric user ID", "");
  const id = Number(manual);
  if (!Number.isInteger(id)) throw new Error("Telegram user ID must be a number");
  return id;
}

async function telegram(token, method, payload) {
  const response = await fetch(`https://api.telegram.org/bot${encodeURIComponent(token)}/${method}`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });
  const data = await response.json();
  if (!response.ok || data.ok !== true) throw new Error(`Telegram ${method} failed: ${data.description ?? response.statusText}`);
  return data.result;
}

async function askRequiredSecret(rl, label) {
  for (;;) {
    const value = (await rl.question(`${label}: `)).trim();
    if (value.length > 0) return value;
  }
}

async function askWithDefault(rl, label, fallback) {
  const answer = (await rl.question(`${label}${fallback ? ` [${fallback}]` : ""}: `)).trim();
  return answer || fallback;
}

async function askAbsolutePath(rl, label, fallback) {
  for (;;) {
    const value = await askWithDefault(rl, label, fallback);
    if (value.startsWith("/")) return value;
    console.log("Please enter an absolute path.");
  }
}

async function askYesNo(rl, label, fallback) {
  const suffix = fallback ? "Y/n" : "y/N";
  const answer = (await rl.question(`${label} [${suffix}]: `)).trim().toLowerCase();
  if (!answer) return fallback;
  return answer === "y" || answer === "yes";
}

function expandHome(path) {
  if (path === "~") return process.env.HOME ?? path;
  if (path.startsWith("~/")) return resolve(process.env.HOME ?? ".", path.slice(2));
  return path;
}

function formatUser(user) {
  const handle = user.username ? ` @${user.username}` : "";
  const name = [user.first_name, user.last_name].filter(Boolean).join(" ");
  return `${user.id}${handle}${name ? ` (${name})` : ""}`;
}

function redactToken(token) {
  const [prefix] = token.split(":");
  return `${prefix}:...`;
}
